sudo: false
language: python

env:
  - PYTHON=2.7 PANDAS=0.19.2
  - PYTHON=3.4 PANDAS=0.18.1
  - PYTHON=3.5 PANDAS=0.19.2 COVERAGE='true'
  - PYTHON=3.6 PANDAS='master' LINT='true'

install:
  - ci/install_trvish.sh

script:
  - pytest -s -v --cov=pandas_msgpack --cov-report xml:/tmp/pytest-cov.xml pandas_msgpack
  - if [ $COVERAGE ]; then codecov ; fi
  - if [ $LINT ]; then flake8 pandas_msgpack -v ; fi
